-- 08_functions.sql
-- Source: Supabase FUNCTIONS.txt
-- Last sync: (Current)
-- DO NOT EDIT MANUALLY

-- Note: Real definitions live in Supabase Studio. This is an inventory.
-- public.activate_plan_on_invoice_paid() LANGUAGE plpgsql SECURITY DEFINER
-- public.activate_plan_trial(p_tenant_id uuid, p_plan text, p_days integer) LANGUAGE plpgsql SECURITY DEFINER
-- public.aggregate_daily_market_price(p_date date) LANGUAGE plpgsql SECURITY DEFINER
-- public.append_tutorial_completed(p_key text, p_value text) LANGUAGE sql SECURITY DEFINER
-- public.auth_user_tenant_ids() LANGUAGE sql SECURITY DEFINER
-- public.auto_resolve_loss_reports() LANGUAGE plpgsql SECURITY INVOKER
-- public.can_manage_delivery_sembako() LANGUAGE sql SECURITY DEFINER
-- public.can_manage_drivers(p_tenant_id uuid) LANGUAGE sql SECURITY DEFINER
-- public.can_manage_finance_sembako() LANGUAGE sql SECURITY DEFINER
-- public.can_manage_inventory_egg(tid uuid) LANGUAGE sql SECURITY DEFINER
-- public.can_manage_inventory_sembako() LANGUAGE sql SECURITY DEFINER
-- public.can_manage_payments(p_tenant_id uuid) LANGUAGE sql SECURITY DEFINER
-- public.can_manage_purchases(p_tenant_id uuid) LANGUAGE sql SECURITY DEFINER
-- public.can_manage_rpa(tid uuid) LANGUAGE sql SECURITY DEFINER
-- public.can_manage_sales(p_tenant_id uuid) LANGUAGE sql SECURITY DEFINER
-- public.can_manage_sales_sembako() LANGUAGE sql SECURITY DEFINER
-- public.can_update_payments(p_tenant_id uuid) LANGUAGE sql SECURITY DEFINER
-- public.can_update_purchases(p_tenant_id uuid) LANGUAGE sql SECURITY DEFINER
-- public.can_update_sales(p_tenant_id uuid) LANGUAGE sql SECURITY DEFINER
-- public.can_write_notifications() LANGUAGE sql SECURITY INVOKER
-- public.check_sembako_transaction_quota() LANGUAGE plpgsql SECURITY INVOKER
-- public.create_new_business(p_business_name text, p_business_vertical text, p_phone text, p_location text) LANGUAGE plpgsql SECURITY DEFINER
-- public.deduct_batch_stock(p_batch_id uuid, p_qty numeric) LANGUAGE plpgsql SECURITY DEFINER
-- public.deduct_egg_stock_on_sale() LANGUAGE plpgsql SECURITY INVOKER
-- public.downgrade_expired_plans() LANGUAGE plpgsql SECURITY DEFINER
-- public.enforce_payment_ceiling() LANGUAGE plpgsql SECURITY INVOKER
-- public.enforce_rpa_invoice_quota() LANGUAGE plpgsql SECURITY DEFINER
-- public.flag_market_price_outlier() LANGUAGE plpgsql SECURITY DEFINER
-- public.generate_egg_invoice_number(p_tenant_id uuid) LANGUAGE plpgsql SECURITY INVOKER
-- public.generate_invoice_number() LANGUAGE plpgsql SECURITY INVOKER
-- public.get_active_ternak_count(p_tenant_id uuid, p_species_group text) LANGUAGE plpgsql SECURITY DEFINER
-- public.get_business_category(p_vertical text) LANGUAGE sql SECURITY INVOKER
-- public.get_invitation_by_token(p_token text) LANGUAGE sql SECURITY DEFINER
-- public.get_kandang_limit(p_tenant_id uuid) LANGUAGE sql SECURITY INVOKER
-- public.get_my_tenant_id() LANGUAGE plpgsql SECURITY DEFINER
-- public.get_my_tenant_ids() LANGUAGE sql SECURITY DEFINER
-- public.get_province_price_trends(p_province text, p_start_date date, p_end_date date) LANGUAGE sql SECURITY DEFINER
-- public.get_public_market_stats() LANGUAGE plpgsql SECURITY DEFINER
-- public.get_ternak_limit(p_tenant_id uuid, p_species_group text) LANGUAGE plpgsql SECURITY DEFINER
-- public.get_user_type_from_vertical(p_vertical text) LANGUAGE sql SECURITY INVOKER
-- public.handle_new_user() LANGUAGE plpgsql SECURITY DEFINER
-- public.handle_user_email_update() LANGUAGE plpgsql SECURITY DEFINER
-- public.has_tenant_access(p_tenant_id uuid) LANGUAGE sql SECURITY DEFINER
-- public.increment_sapi_batch_animal_count(p_batch_id uuid) LANGUAGE plpgsql SECURITY DEFINER
-- public.is_my_tenant(_tenant_id uuid) LANGUAGE plpgsql SECURITY DEFINER
-- public.is_superadmin() LANGUAGE sql SECURITY DEFINER
-- public.is_tenant_member(p_tenant_id uuid) LANGUAGE sql SECURITY DEFINER
-- public.log_audit_action() LANGUAGE plpgsql SECURITY DEFINER
-- public.my_profile_id() LANGUAGE sql SECURITY DEFINER
-- public.my_role() LANGUAGE sql SECURITY DEFINER
-- public.my_role_for(p_tenant_id uuid) LANGUAGE sql SECURITY DEFINER
-- public.my_tenant_id() LANGUAGE sql SECURITY DEFINER
-- public.my_user_type() LANGUAGE sql SECURITY DEFINER
-- public.prevent_app_role_escalation() LANGUAGE plpgsql SECURITY DEFINER
-- public.prevent_profile_privilege_escalation() LANGUAGE plpgsql SECURITY DEFINER
-- public.recalc_sembako_customer_balance(v_customer_id uuid) LANGUAGE plpgsql SECURITY DEFINER
-- public.recalculate_payment_status() LANGUAGE plpgsql SECURITY INVOKER
-- public.record_market_price() LANGUAGE plpgsql SECURITY DEFINER
-- public.rpa_tenant_in_trial(p_tenant_id uuid) LANGUAGE sql SECURITY DEFINER
-- public.set_updated_at() LANGUAGE plpgsql SECURITY INVOKER
-- public.sync_rpa_customer_outstanding() LANGUAGE plpgsql SECURITY DEFINER
-- public.sync_rpa_outstanding() LANGUAGE plpgsql SECURITY INVOKER
-- public.sync_sale_payment() LANGUAGE plpgsql SECURITY INVOKER
-- public.sync_sembako_customer_outstanding() LANGUAGE plpgsql SECURITY DEFINER
-- public.tr_sync_sembako_balance() LANGUAGE plpgsql SECURITY DEFINER
-- public.trg_peternak_generate_task_instances() LANGUAGE plpgsql SECURITY DEFINER
-- public.trg_purchases_sync_market_price() LANGUAGE plpgsql SECURITY DEFINER
-- public.trg_sales_sync_market_price() LANGUAGE plpgsql SECURITY DEFINER
-- public.trg_sales_sync_rpa_outstanding() LANGUAGE plpgsql SECURITY DEFINER
-- public.trg_sapi_breeding_birth_mating() LANGUAGE plpgsql SECURITY DEFINER
-- public.trg_sapi_breeding_health_mark_dead() LANGUAGE plpgsql SECURITY DEFINER
-- public.trg_sapi_breeding_mating_defaults() LANGUAGE plpgsql SECURITY DEFINER
-- public.trg_sapi_breeding_sale_mark_sold() LANGUAGE plpgsql SECURITY DEFINER
-- public.trg_sapi_breeding_weight_sync() LANGUAGE plpgsql SECURITY DEFINER
-- public.trg_sapi_sync_animal_latest_weight() LANGUAGE plpgsql SECURITY DEFINER
-- public.trg_sapi_sync_batch_mortality() LANGUAGE plpgsql SECURITY DEFINER
-- public.update_ai_conversations_updated_at() LANGUAGE plpgsql SECURITY INVOKER
-- public.update_ai_pending_entries_updated_at() LANGUAGE plpgsql SECURITY INVOKER
-- public.update_cycle_summary() LANGUAGE plpgsql SECURITY INVOKER
-- public.update_egg_customer_stats() LANGUAGE plpgsql SECURITY INVOKER
-- public.update_farm_last_transaction() LANGUAGE plpgsql SECURITY INVOKER
-- public.update_sembako_product_stock() LANGUAGE plpgsql SECURITY DEFINER