/**
 * TernakOS Default Task Templates — Domba
 * Penggemukan (~90 hari) dan Breeding (siklus reproduksi).
 * Domba berbeda dari kambing: siklus birahi ±17 hari, kebuntingan ±147 hari,
 * perlu perhatian bulu/wool, dan lebih rentan terhadap parasit.
 *
 * task_type enum: 'pakan' | 'timbang' | 'vaksinasi' | 'kesehatan' | 'kebersihan_kandang' | 'reproduksi' | 'bcs_check' | 'wool_check' | 'lainnya'
 */

// ── TEMPLATE DOMBA PENGGEMUKAN 90 HARI ────────────────────────────────────────

export const TEMPLATE_DOMBA_PENGGEMUKAN_90 = [

  // ── FASE ADAPTASI (Hari 1–14, offset 0–13) ──────────────────────────────

  {
    title: 'Timbang awal (berat masuk)',
    description: 'Timbang semua domba bakalan untuk baseline ADG.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 0,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Cek BCS & kondisi bulu awal',
    description: 'Evaluasi BCS (skala 1–5) dan kondisi bulu/wool domba masuk.',
    task_type: 'bcs_check',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:30:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 0,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Observasi kondisi bakalan',
    description: 'Periksa kondisi fisik, nafsu makan, kuku, dan tanda penyakit.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Beri pakan adaptasi (hijauan 70%)',
    description: 'Hijauan 70% + konsentrat 30%. Domba membutuhkan transisi pakan bertahap.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kotoran, cek kelembaban lantai (domba sensitif terhadap lantai basah).',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Vaksinasi SE + Anthrax',
    description: 'Berikan vaksin SE dan Anthrax sesuai dosis.',
    task_type: 'vaksinasi',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 3,
    phase_end_offset: 3,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Obat cacing + spray anti-ektoparasit',
    description: 'Obat cacing oral + spray kutu/tungau (domba lebih rentan ektoparasit).',
    task_type: 'kesehatan',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 5,
    phase_end_offset: 5,
    phase_label: 'Adaptasi',
  },

  // ── FASE GROWING (Hari 15–75, offset 14–74) ──────────────────────────────

  {
    title: 'Beri pakan pagi (konsentrat 50%)',
    description: 'Pakan pagi: konsentrat 50% + hijauan 50%.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Cek kesehatan harian',
    description: 'Amati nafsu makan, postur, mata, dan kondisi bulu. Domba cenderung menyembunyikan gejala sakit.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kotoran, cek lantai & drainase.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Timbang rutin 2 mingguan',
    description: 'Timbang untuk monitor ADG.',
    task_type: 'timbang',
    recurring_type: 'dua_mingguan',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Cek kondisi bulu/wool',
    description: 'Periksa bulu: ada kutu, tungau, atau tanda jamur kulit (ringworm)? Domba perlu perhatian ekstra.',
    task_type: 'wool_check',
    recurring_type: 'mingguan',
    recurring_days_of_week: [3],
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },

  // ── FASE FINISHER (Hari 76–90, offset 75–89) ─────────────────────────────

  {
    title: 'Beri pakan finisher (konsentrat 60%)',
    description: 'Tingkatkan konsentrat ke 60% untuk percepat penambahan berat.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 75,
    phase_end_offset: 89,
    phase_label: 'Finisher',
  },
  {
    title: 'Timbang mingguan (target panen)',
    description: 'Timbang mingguan untuk konfirmasi target berat panen.',
    task_type: 'timbang',
    recurring_type: 'mingguan',
    recurring_days_of_week: [1],
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 75,
    phase_end_offset: 89,
    phase_label: 'Finisher',
  },
  {
    title: 'Timbang final pra-panen',
    description: 'Timbang final 3 hari sebelum panen.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 87,
    phase_end_offset: 87,
    phase_label: 'Finisher',
  },
]

// ── TEMPLATE DOMBA BREEDING (SIKLUS REPRODUKSI) ──────────────────────────────

export const TEMPLATE_DOMBA_BREEDING = [
  {
    title: 'Deteksi birahi (estrus)',
    description: 'Amati tanda birahi domba: gelisah, menggoyang ekor, vulva bengkak. Siklus birahi domba ±17 hari (lebih pendek dari kambing).',
    task_type: 'reproduksi',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 25,
    phase_label: 'Deteksi Birahi',
  },
  {
    title: 'Evaluasi BCS induk',
    description: 'Pastikan BCS induk 3.0–3.5 sebelum kawin. Perhatikan kondisi bulu dan kuku.',
    task_type: 'bcs_check',
    recurring_type: 'mingguan',
    recurring_days_of_week: [1],
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 25,
    phase_label: 'Deteksi Birahi',
  },
  {
    title: 'Beri pakan induk',
    description: 'Pakan induk: hijauan + konsentrat protein tinggi.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 200,
    phase_label: 'Pemeliharaan',
  },
  {
    title: 'Cek kesehatan & kondisi bulu induk',
    description: 'Cek kondisi fisik induk termasuk bulu, ambing, dan kuku.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 200,
    phase_label: 'Pemeliharaan',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kandang, pastikan lantai kering (domba sensitif lantai basah).',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 200,
    phase_label: 'Pemeliharaan',
  },
  {
    title: 'Cek kebuntingan (palpasi/USG)',
    description: 'Konfirmasi kebuntingan 45 hari setelah kawin. Masa bunting domba ±147 hari.',
    task_type: 'reproduksi',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 70,
    phase_end_offset: 70,
    phase_label: 'Kebuntingan',
  },
  {
    title: 'Cek kondisi bulu pra-kelahiran',
    description: 'Cukur bulu di sekitar ambing dan area belakang menjelang kelahiran.',
    task_type: 'wool_check',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 160,
    phase_end_offset: 160,
    phase_label: 'Kelahiran',
  },
  {
    title: 'Persiapan kandang kelahiran',
    description: 'Siapkan kandang bersalin: bersihkan, beri alas kering, sediakan handuk & iodine.',
    task_type: 'lainnya',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: false,
    phase_start_offset: 165,
    phase_end_offset: 165,
    phase_label: 'Kelahiran',
  },
]
